name: Deploy Feed Service

on:
  [push]

env:
  AZURE_FUNCTIONAPP_NAME: 'microfrontend-feed-service' # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '/azure-function-pilet-feed'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '2.1'              # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: 'Login Azure'
      uses: azure/login@v1
      with:
        creds:  ${{ secrets.AZURE_CREDENTIALS_PRIVATE }}
    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/bin/Release/netcoreapp2.1/'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
